author: Akash Aggarwal
name: Akash Aggarwal - Software Developer
markdown: kramdown
plugins: 
  - jekyll-sitemap
social-network-links:
reddit: zyabxwcd
linkedin: akashaggarwal13
google_analytics: "UA-127088760-1"
